name: Build

on:
  push:
    branches:
      - master
#    paths:
#      - 'sonar-scanner/src/javascript'
#      - 'sonar-scanner/src/php'
#      - 'sonar-scanner/src/python'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarQubeScanmonojavascript:
    name: sonarQubeScanmonojavascript
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan mono javascript
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_MONOJAVASCRIPT }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: sonar-scanner/src/javascript

  sonarQubeScanmonophp:
    name: sonarQubeScanmonophp
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan mono php
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_MONOPHP }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: sonar-scanner/src/php

  sonarQubeScanmonopython:
    name: sonarQubeScanmonopython
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan mono python
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_MONOPYTHON }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: sonar-scanner/src/python
